configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/sra.smk"
include: "rules/map.smk"
include: "rules/peak.smk"
include: "rules/bw.smk"
include: "rules/count.smk"

rule all:
    input:
        expand("{out_}", out_ = outputs)